import Foundation

/// Renders and updates the SiteBlocker-managed section of an `/etc/hosts`-style file.
///
/// The managed section is delimited by marker comments so we can safely add/remove it
/// without disturbing anything else the user (or the system) put in the file.
public enum HostsFile {
    public static let beginMarker = "# >>> SiteBlocker managed block start (do not edit by hand) >>>"
    public static let endMarker = "# <<< SiteBlocker managed block end <<<"

    /// The redirect addresses used to null-route a blocked host.
    static let redirectIPv4 = "127.0.0.1"
    static let redirectIPv6 = "::1"

    /// Generate the host lines for a list of canonical domains (expanding `www.` and IPv4/IPv6).
    /// Output is de-duplicated while preserving first-seen order.
    public static func entries(for domains: [String]) -> [String] {
        var lines: [String] = []
        var seen = Set<String>()
        for domain in domains {
            for host in Domain.hostnames(for: domain) {
                for ip in [redirectIPv4, redirectIPv6] {
                    let line = "\(ip)\t\(host)"
                    if seen.insert(line).inserted {
                        lines.append(line)
                    }
                }
            }
        }
        return lines
    }

    /// Parse the set of hostnames currently null-routed inside the managed section of a hosts file.
    /// This is the *truth* about what is blocked right now (e.g. after the daemon updated it while
    /// the app was closed, or after an external edit).
    public static func blockedHostnames(in content: String) -> Set<String> {
        var hosts = Set<String>()
        var inside = false
        for rawLine in content.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line == beginMarker { inside = true; continue }
            if line == endMarker { break }
            guard inside, !line.isEmpty, !line.hasPrefix("#") else { continue }
            // Lines look like "127.0.0.1\texample.com" — take the host (last whitespace field).
            let fields = line.split(whereSeparator: { $0 == " " || $0 == "\t" })
            if fields.count >= 2, let host = fields.last {
                hosts.insert(String(host))
            }
        }
        return hosts
    }

    /// Remove any existing managed section (markers + their contents) from `existing`,
    /// returning the surrounding content with trailing blank lines trimmed to a single newline.
    public static func stripped(_ existing: String) -> String {
        let lines = existing.components(separatedBy: "\n")
        var kept: [String] = []
        var insideManaged = false
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed == beginMarker {
                insideManaged = true
                continue
            }
            if trimmed == endMarker {
                insideManaged = false
                continue
            }
            if insideManaged { continue }
            kept.append(line)
        }

        // Collapse trailing whitespace-only lines.
        while let last = kept.last, last.trimmingCharacters(in: .whitespaces).isEmpty {
            kept.removeLast()
        }
        return kept.joined(separator: "\n")
    }

    /// Produce the full file contents for `existing` with the managed section reflecting
    /// `blockedDomains`. Removing all blocks leaves the file clean (no empty managed section).
    public static func render(existing: String, blockedDomains: [String]) -> String {
        let base = stripped(existing)
        let entries = entries(for: blockedDomains)

        guard !entries.isEmpty else {
            // Nothing to block: just the cleaned base, with a single trailing newline.
            return base.isEmpty ? "" : base + "\n"
        }

        var section: [String] = []
        section.append(beginMarker)
        section.append("# Generated by SiteBlocker. Entries appear only while a block is active.")
        section.append(contentsOf: entries)
        section.append(endMarker)
        let sectionText = section.joined(separator: "\n")

        if base.isEmpty {
            return sectionText + "\n"
        }
        return base + "\n\n" + sectionText + "\n"
    }
}
